# Generated by Django 4.2.5 on 2023-12-16 13:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_productorder_cart_item_productorder_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='cart_item',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='core.cartitem'),
            preserve_default=False,
        ),
    ]
