# Generated by Django 4.2.5 on 2023-12-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_productorder_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='user',
        ),
    ]
