# Generated by Django 4.2.5 on 2023-12-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_productorder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='cart_item',
        ),
    ]
