# Generated by Django 4.2.5 on 2023-12-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
