# Generated by Django 4.2.5 on 2023-12-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_coupon_minimum_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='minimum_purchase',
            field=models.PositiveIntegerField(),
        ),
    ]
