# Generated by Django 4.2.5 on 2023-12-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_coupon_minimum_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='minimum_purchase',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
