# Generated by Django 4.2.5 on 2024-01-09 04:53

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_coupon_used_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img1_cropping',
            field=image_cropping.fields.ImageRatioField('product_img1', '800x800', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='product img1 cropping'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img2_cropping',
            field=image_cropping.fields.ImageRatioField('product_img2', '800x800', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='product img2 cropping'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img3_cropping',
            field=image_cropping.fields.ImageRatioField('product_img3', '800x800', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='product img3 cropping'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img1',
            field=image_cropping.fields.ImageCropField(upload_to='media/product/img1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img2',
            field=image_cropping.fields.ImageCropField(upload_to='media/product/img2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img3',
            field=image_cropping.fields.ImageCropField(upload_to='media/product/img3'),
        ),
    ]
