# Generated by Django 4.2.5 on 2024-01-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_remove_product_product_img1_cropping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.ImageField(blank=True, null=True, upload_to='media/banner/image')),
                ('subtitle', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
