# Generated by Django 4.2.5 on 2024-01-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
