# Generated by Django 4.2.5 on 2024-01-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_alter_banner_banner_img_alter_banner_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='days_difference',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
