# Generated by Django 4.2.5 on 2023-12-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressus',
            old_name='address_1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='addressus',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='addressus',
            name='last_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
