# Generated by Django 4.2.5 on 2023-12-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_address_1_addressus_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='user-icon-big.png', null=True, upload_to='media/user'),
        ),
    ]
