# Generated by Django 4.2.5 on 2023-12-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_addressus_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressus',
            old_name='address',
            new_name='address1',
        ),
    ]
