# Generated by Django 4.2.5 on 2023-12-07 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_address_addressus_address1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressus',
            name='address1',
        ),
        migrations.AddField(
            model_name='addressus',
            name='address_1',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
