# Generated by Django 4.2.5 on 2023-12-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_addressus_address1_addressus_address_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='user.addressus'),
        ),
    ]
