# Generated by Django 4.2.5 on 2023-12-08 01:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_userprofile_address_userprofile_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='addresses',
        ),
        migrations.AddField(
            model_name='addressus',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addressus',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='user.userprofile'),
            preserve_default=False,
        ),
    ]
