# Generated by Django 4.2.5 on 2023-12-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
        ('user', '0011_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist_items', to='adminapp.product'),
        ),
    ]
