# Generated by Django 4.2.5 on 2023-12-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_userprofile_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='New', max_length=10),
        ),
    ]
