# Generated by Django 4.2.5 on 2023-12-30 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_wallet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
    ]
